### ISSUE TITLE
get_menus() 方法返回空数据，似乎是不同的 api？

### ISSUE THREAD

**Issue by CtheSky** [LKI/xixiang#2]
公司最近用上了熙香点餐，今天尝试了一下用 python 来调用，发现会有报错：

![try_xixiang](https://user-images.githubusercontent.com/13807244/68832294-8a901100-06eb-11ea-8e96-701fc099123d.png)

我自己登录[网页版](http://platform.xixiang000.com/)，看了一下具体的请求：

![xixiang_web](https://user-images.githubusercontent.com/13807244/68832524-228dfa80-06ec-11ea-8802-d911efcb407f.png)

感觉好像用的不是库里面的这个请求和参数，用的是 `/cookbook` 这个接口：
```python
def get_menus(self):
    return xixiang.Menu.load(self.get(xixiang.urls.list_menu_url))
```

我想尝试支持一下，但是找了一下官方的 api 文档也没有找到，想问下作者是自己研究的网页版接口写的吗？还是有对应的文档？感觉像是熙香的用法不一样，我们是每天有两餐可以点，然后具体选商家再选套餐这样。

**Comment by liriansu-opus** [comment]
感谢 issue。

官方没提供文档，我是自己抓的网页版接口写的…

接口报错的原因应该是熙香在最近更新了接口。
因为最近我都在用[美餐](https://github.com/LKI/meican)，所以这个项目有一阵没维护了…

具体的接口这两天我修一下，修好了发个新版。

（用法看了一下，应该是一样的，每天点中饭午饭、选商家选套餐）

**Comment by liriansu-opus** [comment]
重新适配了他们的api，现在可用了
